version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb
    environment:
      MARIADB_DATABASE: test
      # You should definitely change the password in production
      MARIADB_PASSWORD: test
      MARIADB_USER: test
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###